# Generated by Django 5.2.3 on 2025-06-12 05:01

import accounts.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_region'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodeEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=200)),
                ('expire_date', models.DateTimeField(default=accounts.models.default_expire_date)),
            ],
            options={
                'verbose_name': 'Email Code',
                'verbose_name_plural': 'Email Codes',
                'db_table': 'CodeEmail',
            },
        ),
        migrations.CreateModel(
            name='CodePassword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10)),
                ('expire_date', models.DateTimeField(default=accounts.models.default_expire_date)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Password Code',
                'verbose_name_plural': 'Password Codes',
                'db_table': 'CodePassword',
            },
        ),
    ]
