# Generated by Django 5.2.3 on 2025-06-12 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_temporaryuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='temporaryuser',
            name='password',
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
    ]
