# Generated by Django 5.2.3 on 2025-06-12 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_temporaryuser_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='temporaryuser',
            name='re_password',
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
    ]
