# Generated by Django 5.2.3 on 2025-06-12 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_user_google_id'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='temporaryuser',
            table='TemporaryUser',
        ),
    ]
