# Generated by Django 5.2.3 on 2025-06-16 18:00

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_emailverification'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecentActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CREATE', 'Created'), ('UPDATE', 'Updated'), ('DELETE', 'Deleted')], max_length=10)),
                ('model_name', models.CharField(choices=[('Product', 'Product'), ('PlantedProduct', 'Planted Product'), ('Region', 'Region')], max_length=50)),
                ('object_id', models.PositiveIntegerField()),
                ('object_name', models.CharField(max_length=255)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recent_activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Recent Activity',
                'verbose_name_plural': 'Recent Activities',
                'db_table': 'recent_activities',
                'ordering': ['-timestamp'],
            },
        ),
    ]
