# Generated by Django 5.2.3 on 2025-06-16 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_recentactivity'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='recentactivity',
            table='Recent Activities',
        ),
    ]
