name: CD -> VPS

on:
  workflow_run:
    workflows:
      - "CI"
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest

    if: ${{ github.event.workflow_run.conclusion == 'success' && github.actor != 'github-actions[bot]' }}

    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v3

      - name: "Deleting old images and containers and creating new ones on VPS"
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: '22'
          script: |
            set -e
            cd /home/${{ secrets.SERVER_USER }}/agroconnect

            # Stash local changes if any
            if ! git diff-index --quiet HEAD --; then
                echo "Local changes found, stashing..."
                git stash push -m "auto-cd-stash" || true
            fi

            # Pull latest main
            git fetch origin main
            git reset --hard origin/main
            
            sudo docker compose -p "$PROJECT" down --volumes --remove-orphans

            sudo docker images --format '{{.Repository}} {{.ID}}' | awk -v prefix="$PROJECT" '$1 ~ "^"prefix {print $2}' | xargs -r sudo docker rmi
            sudo docker volume ls --format '{{.Name}}' | grep "^${PROJECT}_" | xargs -r sudo docker volume rm
            sudo docker network ls --format '{{.Name}}' | grep "^${PROJECT}_" | xargs -r sudo docker network rm
            sudo docker builder prune -af

