# Generated by Django 5.2.3 on 2025-06-16 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='plantedproduct',
            table='Planted Products',
        ),
    ]
