# Generated by Django 5.2.3 on 2025-06-16 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_plantedproduct_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='plantedproduct',
            name='expecting_weight',
            field=models.DecimalField(decimal_places=3, default=None, max_digits=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='plantedproduct',
            name='planting_area',
            field=models.DecimalField(decimal_places=3, default=None, max_digits=15),
            preserve_default=False,
        ),
    ]
